### PR TITLE
[pm] F: Kernel Semaphore Semget

### LINKED ISSUE #388: [pm] Implement Semaphore Get
## Description
Implement a function to get Semaphores.

### kernel_semget

`int kcall_semget (int key)` 

**Do** 
If key already exist, associate current process at semaphore, else, create a semaphore with the key.

**Return**
* `-1`: Failed
* `0`: Semaphore exist
* `Id` : Created semaphore ID

### Change:
*  `src/kernel/kcall/sem/semget.c`
* `src/servers/test/src/test.rs`

Root issue: #385

### PR DESCRIPTION
**Pull request by rafael0121**
## Description

- This PR closes #388 

## Summary of Changes

- Changed return in function `semaphore_get()`, now this function return the key if a key was found by `key_check()`.
- Implemented Semaphore get function and improve test.

### CODE REVIEW

File: src/kernel/kcall/sem/semget.c [hunk 1]
```diff
@@ -20,8 +20,29 @@
...
 int kcall_semget(unsigned key)
 {
-    // TODO: https://github.com/nanvix/microkernel/issues/388
+    int ret;
+    int semid;
 
-    // Return to test syscall.
-    return (key);
+    // Try create a semaphore.
+    ret = semaphore_create(key);
```
Comment (ppenna) [inline src/kernel/kcall/sem/semget.c:27]: Please perform declaration and initialization all together whenever possible. This is a good practice to prevent undefined behavior.

File: src/kernel/kcall/sem/semget.c [hunk 2]
```diff
@@ -20,8 +20,29 @@
...
+            return (0);
+        case -1:
+            return (-1);
+        default:
+            semid = ret;
+            break;
+    }
+
+    // Try get semaphore.
+    ret = semaphore_get(semid);
```
Comment (ppenna) [inline src/kernel/kcall/sem/semget.c:39]: Please perform declaration and initialization all together whenever possible. This is a good practice to prevent undefined behavior.

File: src/kernel/kcall/sem/semget.c (hunk 1 above)
Comment (rafael0121) [reply src/kernel/kcall/sem/semget.c]: Done.

File: src/kernel/kcall/sem/semget.c (hunk 2 above)
Comment (rafael0121) [reply src/kernel/kcall/sem/semget.c:38]: Done.
