### PR TITLE
[pm] F: Feature kernel semaphore semop

### LINKED ISSUE #392: [pm] Implement Semaphore Handler
## Description

Implement a function to do operations in semaphores.

### kernel_semop

`int kcall_semop (int id, int op)`

**Do**
Verify if process can operate in semaphore (id), and operate (op):
* `0`: Up
* `1`: Down
* `2`: Try Lock

**Return**
* `0`: Success
* `-1`: Failed

### Change:
*  `src/kernel/kcall/sem/semop.c`
* `src/servers/test/src/test.rs`

Root issue: #385

### PR DESCRIPTION
**Pull request by rafael0121**
## Description

- This PR closes #392

## Summary of Changes

- Improve comments and remove legacy functions, also fix return of the semctl and semget, adding default return errno.
- Implement semop function and test, also improve other semctl and semget tests, adding constants and readability.
- Create kernel's semaphore and init semaphore table, fix bugs due to legacy functions.

## Files Affected:

- include/nanvix/kernel/pm/semaphore.h
- src/kernel/kcall/mod.c
- src/kernel/kcall/sem/semctl.c
- src/kernel/kcall/sem/semget.c
- src/kernel/kcall/sem/semop.c
- src/kernel/pm/process.c
- src/kernel/pm/semaphore.c
- src/servers/test/src/test.rs

### CODE REVIEW

File: include/nanvix/kernel/pm/semaphore.h [hunk 1]
```diff
@@ -59,7 +71,7 @@ struct semaphore {
  * fields of the semaphore pointed to by @p sem. The initial value
  * of the semaphore is set to @p x in the initialization.
  *
- * @param sem Target semaphore.
+ * @p sem Semaphore structure.
  * @param x   Initial semaphore value.
  */
 static inline void semaphore_init(struct semaphore *sem, int x)
```
Comment (ppenna) [inline include/nanvix/kernel/pm/semaphore.h:77]: Could you make this a non-inline function?

File: src/kernel/kcall/sem/semget.c [hunk 2]
```diff
@@ -34,28 +20,21 @@
...
-            return (ret);
-        case SEMAPHORE_ENOBUFS:
+        case -EEXIST:
+            return (semaphore_getid(key));
+        case -ENOBUFS:
             return (-ENOBUFS);
         default:
             semid = ret;
             break;
     }
```
Comment (ppenna) [inline src/kernel/kcall/sem/semget.c:36]: The switch case logic here is dangerous. If the implementation of semaphore_create() changes so that it fails with a different error code besides EEXIST and ENOBUFS, you would fall through and run semaphore_get(). If you replace this logic with an if-else statement you avoid this.

File: src/kernel/kcall/sem/semop.c [hunk 3]
```diff
@@ -11,6 +11,14 @@
 #include <nanvix/kernel/pm/process.h>
 #include <nanvix/kernel/pm/semaphore.h>
 
+/*============================================================================*
+ * Constants                                                                  *
+ *============================================================================*/
+
+#define SEMAPHORE_UP 0
+#define SEMAPHORE_DOWN 1
+#define SEMAPHORE_TRYLOCK 2
```
Comment (ppenna) [inline src/kernel/kcall/sem/semop.c:20]: These should be in a globla header file, as a C-application will rely on these values to invoke the system call.

File: src/kernel/pm/process.c [hunk 4]
```diff
@@ -227,6 +228,9 @@ void process_wakeup(struct process *p)
     thread_wakeup_all(p->pid);
 }
 
+int kernel_semaphore;
+int user_semaphore;
```
Comment (ppenna) [inline src/kernel/pm/process.c:232]: Move these to the begin of the file, just before the private variables section. Initialize these variables statically with an invalid value to avoid UB.

**Review by ppenna — COMMENTED** [review]
We are almost there  :)

File: src/kernel/kcall/sem/semop.c (hunk 3 above)
Comment (rafael0121) [reply src/kernel/kcall/sem/semop.c:20]: Okay.

File: src/kernel/kcall/sem/semget.c (hunk 2 above)
Comment (rafael0121) [reply src/kernel/kcall/sem/semget.c:36]: I agree, is really dangerous.

File: include/nanvix/kernel/pm/semaphore.h (hunk 1 above)
Comment (rafael0121) [reply include/nanvix/kernel/pm/semaphore.h:77]: I rewrite semaphore_init() inline in semaphore_set() now.

File: src/kernel/pm/process.c (hunk 4 above)
Comment (rafael0121) [reply src/kernel/pm/process.c:232]: They are declared on semaphore.h as extern variables. So i deleted the declaration in semaphore.h and declared and initialized in process.c.

File: src/kernel/pm/process.c [hunk 5]
```diff
@@ -247,4 +251,11 @@ void process_init(vmem_t root_vmem)
     kernel->vmem = (vmem_t)root_vmem;
     kernel->active = true;
     thread_init();
+
+    // Initialize semaphore table.
+    semtable_init();
+
+    // Initialize Kernel's semaphores.
+    kernel_semaphore = semaphore_create(0);
+    user_semaphore = semaphore_create(1);
```
[the remark this answers is not in the document]
Comment (rafael0121) [reply src/kernel/pm/process.c:260]: Okay.

File: include/nanvix/kernel/pm/semaphore.h [hunk 6]
```diff
@@ -38,19 +50,19 @@ struct semaphore {
...
- *
- * @param x Initial value for semaphore.
+ * @brief Kernel's semaphore
  */
-#define SEMAPHORE_INITIALIZER(x)                                               \
-    {                                                                          \
-        .count = (x), .cond = COND_INITIALIZER,                                \
-    }
+extern int kernel_semaphore;
+extern int user_semaphore;
```
[the remark this answers is not in the document]
Comment (rafael0121) [reply include/nanvix/kernel/pm/semaphore.h:61]: They existed, but i removed the declaration now, see review below.

**Review by ppenna — APPROVED** [review]
LGMT
